ALTER TABLE collections ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;
ALTER TABLE orders      ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;
ALTER TABLE payments    ADD COLUMN deleted_at DATETIME NULL DEFAULT NULL;
